name: Generate Rust Docs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Generate documentation
      run: cargo doc --no-deps

    - name: Get Rust version
      id: rust_version
      run: |
        VERSION=$(rustc --version | awk '{print $2}' | tr '.' '_')
        echo "::set-output name=version::v$VERSION"

    - name: Get Repository Name
      id: repo_name
      run: echo "::set-output name=name::$(basename -s .git `git config --get remote.origin.url`)"

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to rust_document
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git clone git@github.com:pentacle8/rust_document.git
        cd rust_document
        git checkout -b ${{ steps.repo_name.outputs.name }}_${{ steps.rust_version.outputs.version }}
        cp -r ../target/doc/* .
        git add .
        git commit -m "Update documentation"
        git push origin ${{ steps.repo_name.outputs.name }}_${{ steps.rust_version.outputs.version }}
